name: Test2341
favicon: null
layout_spectrum: 0.46962
typography_spectrum: 1
title: This is very testy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#993333'
    - '#ffffcc'
    - '#006633'
    - '#9d7161'
    - '#92a67a'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
