name: Test2341
favicon: null
layout_spectrum: 0.01167
typography_spectrum: 0.15203
title: This is very testy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#993333'
    - '#ffffcc'
    - '#006633'
    - '#9d7161'
    - '#92a67a'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
