name: Test2341
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15203
title: This is very testy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#993333'
    - '#ffffcc'
    - '#006633'
    - '#9d7161'
    - '#92a67a'
  brandStrength: 0.5
  lightness: 0.9860103221144527
  saturation: 0.8649052337277681
  rhythmicContrast: 0.39449305017478764
purpose: []
